name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      working-directory: ./monitoring-service
      run: docker build . --file Dockerfile --tag monitoring-service:$(date +%s)
